# Generated by Django 4.2 on 2023-04-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['qid']},
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='big_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='similar_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='small_category',
            field=models.CharField(max_length=100),
        ),
    ]
