# Generated by Django 4.2 on 2023-04-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_problem_options_remove_problem_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobt1',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('similar_answer', models.TextField()),
                ('content', models.TextField()),
                ('appearance_date', models.TextField()),
                ('small_category', models.TextField()),
                ('big_category', models.TextField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'hobt_1',
                'ordering': ['qid'],
            },
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='appearance_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='big_category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='similar_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='small_category',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='problem',
            table='exam_problem',
        ),
    ]
