# Generated by Django 4.2 on 2023-04-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_hobt1_alter_problem_options_alter_problem_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
