# Generated by Django 4.2 on 2023-04-25 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HobtDict',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False, verbose_name='문제 번호')),
                ('answer', models.CharField(max_length=255, verbose_name='정답')),
                ('similar_answer', models.CharField(blank=True, max_length=255, verbose_name='유사 답안')),
                ('content', models.TextField(verbose_name='문제 내용')),
                ('appearance_date', models.CharField(blank=True, max_length=255, verbose_name='출제 연도 예/2020년 1회 실기')),
                ('small_category', models.CharField(blank=True, max_length=255, verbose_name='소 분류')),
                ('big_category', models.CharField(blank=True, max_length=255, verbose_name='대 분류')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='like_hobt_dict', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
