# Generated by Django 4.2 on 2023-04-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobt_dict', '0002_alter_hobtdict_author_alter_hobtdict_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobtdict',
            name='big_category',
            field=models.CharField(blank=True, choices=[('SQL 응용', 'SQL 응용'), ('데이터 입출력 구현', '데이터 입출력 구현'), ('서버 프로그램 구현', '서버 프로그램 구현'), ('소프트웨어 개발 보안 구축', '소프트웨어 개발 보안 구축'), ('애플리케이션 테스트 관리', '애플리케이션 테스트 관리'), ('요구사항 확인', '요구사항 확인'), ('응용 SW 기초 기술 활용', '응용 SW 기초 기술 활용'), ('인터페이스 구현', '인터페이스 구현'), ('정보처리 실무 일반(기타)', '정보처리 실무 일반(기타)'), ('제품 소프트웨어 패키징', '제품 소프트웨어 패키징'), ('통합 구현', '통합 구현'), ('프로그래밍 언어 활용', '프로그래밍 언어 활용'), ('화면 설계', '화면 설계')], max_length=255, verbose_name='대 분류'),
        ),
    ]
