# Generated by Django 4.2 on 2023-04-28 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hobt_dict', '0003_alter_hobtdict_big_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobtdict',
            name='appearance_date',
            field=models.CharField(blank=True, choices=[('2020년 1회 실기', '2020년 1회 실기'), ('2020년 2회 실기', '2020년 2회 실기'), ('2020년 3회 실기', '2020년 3회 실기'), ('2020년 4회 실기', '2020년 4회 실기'), ('2021년 1회 실기', '2021년 1회 실기'), ('2021년 2회 실기', '2021년 2회 실기'), ('2021년 3회 실기', '2021년 3회 실기'), ('2022년 1회 실기', '2022년 1회 실기'), ('2022년 2회 실기', '2022년 2회 실기'), ('기출 예상 문제', '기출 예상 문제'), ('2020년 1회 필기', '2020년 1회 필기'), ('2020년 2회 필기', '2020년 2회 필기'), ('2020년 3회 필기', '2020년 3회 필기'), ('2021년 1회 필기', '2021년 1회 필기'), ('2021년 2회 필기', '2021년 2회 필기'), ('2021년 3회 필기', '2021년 3회 필기'), ('2022년 1회 필기', '2022년 1회 필기'), ('2022년 2회 필기', '2022년 2회 필기')], max_length=255, verbose_name='출제 유형'),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False, verbose_name='문제 번호')),
                ('answer', models.CharField(max_length=255, verbose_name='정답')),
                ('similar_answer', models.CharField(blank=True, max_length=255, verbose_name='유사 답안')),
                ('content', models.TextField(verbose_name='문제 내용')),
                ('appearance_date', models.CharField(blank=True, choices=[('2020년 1회 실기', '2020년 1회 실기'), ('2020년 2회 실기', '2020년 2회 실기'), ('2020년 3회 실기', '2020년 3회 실기'), ('2020년 4회 실기', '2020년 4회 실기'), ('2021년 1회 실기', '2021년 1회 실기'), ('2021년 2회 실기', '2021년 2회 실기'), ('2021년 3회 실기', '2021년 3회 실기'), ('2022년 1회 실기', '2022년 1회 실기'), ('2022년 2회 실기', '2022년 2회 실기'), ('기출 예상 문제', '기출 예상 문제'), ('2020년 1회 필기', '2020년 1회 필기'), ('2020년 2회 필기', '2020년 2회 필기'), ('2020년 3회 필기', '2020년 3회 필기'), ('2021년 1회 필기', '2021년 1회 필기'), ('2021년 2회 필기', '2021년 2회 필기'), ('2021년 3회 필기', '2021년 3회 필기'), ('2022년 1회 필기', '2022년 1회 필기'), ('2022년 2회 필기', '2022년 2회 필기')], max_length=255, verbose_name='출제 유형')),
                ('small_category', models.CharField(blank=True, max_length=255, verbose_name='소 분류')),
                ('big_category', models.CharField(blank=True, choices=[('SQL 응용', 'SQL 응용'), ('데이터 입출력 구현', '데이터 입출력 구현'), ('서버 프로그램 구현', '서버 프로그램 구현'), ('소프트웨어 개발 보안 구축', '소프트웨어 개발 보안 구축'), ('애플리케이션 테스트 관리', '애플리케이션 테스트 관리'), ('요구사항 확인', '요구사항 확인'), ('응용 SW 기초 기술 활용', '응용 SW 기초 기술 활용'), ('인터페이스 구현', '인터페이스 구현'), ('정보처리 실무 일반(기타)', '정보처리 실무 일반(기타)'), ('제품 소프트웨어 패키징', '제품 소프트웨어 패키징'), ('통합 구현', '통합 구현'), ('프로그래밍 언어 활용', '프로그래밍 언어 활용'), ('화면 설계', '화면 설계')], max_length=255, verbose_name='대 분류')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_problem',
            },
        ),
    ]
