# Generated by Django 4.2 on 2023-05-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobt_dict', '0004_alter_hobtdict_appearance_date_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobtdict',
            name='subject',
            field=models.CharField(blank=True, choices=[('ADsP', 'ADsP'), ('정보처리기사', '정보처리기사')], max_length=255, verbose_name='과목'),
        ),
    ]
