# Generated by Django 4.2 on 2023-05-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobt_dict', '0005_hobtdict_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobtdict',
            name='subject',
            field=models.CharField(blank=True, choices=[('ADsP', 'ADsP'), ('정보처리기사', '정보처리기사')], default='Undetermined', max_length=255, verbose_name='과목'),
        ),
    ]
